# Generated by Django 6.0.7 on 2026-07-08 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('admission', 'Student Admission Form'), ('marksheet', 'Marksheet / Grade Sheet'), ('receipt', 'Fee Receipt')], max_length=20)),
                ('file', models.FileField(upload_to='ocr_documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved & Processed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OCRExtractionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_text', models.TextField(blank=True)),
                ('raw_json_data', models.JSONField(blank=True, default=dict, help_text='Parsed fields (e.g. name, marks, total)')),
                ('ocr_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_result', to='ocr_app.ocrdocument')),
            ],
        ),
    ]
